[package]
name = "n2t-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
logos = "0.12.0"
tokenizer = { git = "https://github.com/eelias13/tokenizer", version = "0.1.0" }
hardware-sim = { git = "https://github.com/eelias13/hardware-sim", version = "0.1.0" }
